# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: clwe1s9eh-mp-taco
  namespace: clwe1s9eh
spec:
  clusterName: clwe1s9eh
  replicas: 3
  template:
    metadata:
      labels:
            servicemesh: enabled
            taco-ingress-gateway: enabled
            taco-lma: enabled
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
          name: clwe1s9eh-mp-taco
          namespace: clwe1s9eh
      clusterName: clwe1s9eh
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachinePool
        name: clwe1s9eh-mp-taco
        namespace: clwe1s9eh
      version: v1.22.5

